### ISSUE TITLE
Cards are duplicated

### ISSUE THREAD

**Issue by unnderbar** [numo-labs/isearch-ui#58]
<img width="1382" alt="skarmavbild 2016-04-01 kl 10 42 09" src="https://cloud.githubusercontent.com/assets/242945/14202109/7ee8b418-f7f6-11e5-99c0-4e166020560e.png">

After interacting with filter tiles the remaining filters and articles are duplicated.

**Comment by nelsonic** [comment]
@unnderbar which version of the app where you seeing this in?
I *think* @nikhilaravi corrected this in [**0.5**](https://www.tcdl.io/isearch/0.5/index.html) ...

**Comment by nikhilaravi** [comment]
@nelsonic I think I corrected it too but I can check

**Comment by unnderbar** [comment]
It's version 0,5. It still happens when I press no. @nikhilaravi @nelsonic

**Comment by nikhilaravi** [comment]
this has been fixed now!
